const path = require('node:path');

module.exports = {
    banner: '// Generated by typed-scss-modules. Do not edit.',
    exportType: 'default',
    nameFormat: ['camel'],
    // Resolve the '@/...' alias used in `@import '@/common/...'` statements
    // (mirrors the '@' -> 'src' alias configured in vite.config.ts / tsconfig.json).
    aliasPrefixes: {
        '@/': path.resolve(__dirname, 'src') + '/',
    },
};
